name: review-delete

on:
  pull_request:
    types: [closed]
    branches-ignore:
      - 'master'

jobs:
  destroy_review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: get-branch-name-sanitized
        name: Sanitize branch name
        shell: bash
        run: echo "::set-output name=branch::$(jq --raw-output .pull_request.head.ref "$GITHUB_EVENT_PATH" | sed 's/\//-/g')"
      - env:
          AUTH_SECRET_KEY: ${{ secrets.AUTH_SECRET_KEY }}
          AUTH_CLIENT_ID: ${{ secrets.AUTH_CLIENT_ID }}
          AWS_DEFAULT_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.REVIEW_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.REVIEW_AWS_SECRET_ACCESS_KEY }}
        run: |
          cat << EOF > backend.tf
          terraform {
            backend "s3" {
              bucket = "fp-review-terraform-state"
              region = "us-east-1"
              key = "${{ steps.get-branch-name-sanitized.outputs.branch }}.tfstate"
            }
          }
          EOF
      - run: cat backend.tf
      - run: cat main.tf
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.16
          tf_actions_subcommand: 'init'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.REVIEW_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.REVIEW_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
      - name: 'Terraform Destroy'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.16
          tf_actions_subcommand: 'destroy'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.REVIEW_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.REVIEW_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
