name: review-delete

on:
  pull_request:
    types: [closed]
    branches-ignore:
      - 'master'

jobs:
  destroy_review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo $(jq --raw-output .pull_request.head.ref "$GITHUB_EVENT_PATH") # source branch of PR merge
